[tools]
difftastic = "latest"
fd = "latest"
github-cli = "latest"
glow = "latest"
helix = "latest"
jj = "latest"
jjui = "latest"
node = "latest"
prettier = "latest"
ripgrep = "latest"
ruff = "latest"
usage = "latest"
uv = "latest"
xh = "latest"

# language servers
lua-language-server = "latest"
"npm:@vue/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:basedpyright" = "latest"
taplo = "latest"
"ubi:astral-sh/ty" = "latest"

# sysadmin
aws-cli = "latest"
k9s = "latest"
kubectx = "latest"
qdns = "latest"
"ubi:karol-broda/snitch" = "latest"
"github:hmans/beans" = "latest"
