[tools]
aws-cli = "latest"
claude = "latest"
difftastic = "latest"
fd = "latest"
github-cli = "latest"
helix = "latest"
jj = "latest"
jjui = "latest"
k9s = "latest"
kubectx = "latest"
lua-language-server = "latest"
node = "latest"
"npm:@vue/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:basedpyright" = "latest"
prettier = "latest"
qdns = "latest"
ripgrep = "latest"
ruff = "latest"
taplo = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
